module.exports={
    default:{
        require:[
            'step-definition/*.js',
            'hooks/*.js'
        ],
        format:['progress',
            '@cucumber/html-formatter:reports/report.html'
        ],
        timeout:60000
    }
};