module.exports={
    default:{
        require:[
            'step-definition/*.js',
            'hooks/*.js'
        ],
        format:['progress',
            "allure-cucumberjs/reporter",
            'html:reports/report.html',
        ],
        timeout:60000
    }
};